<a href="https://colab.research.google.com/github/shecheeyee/PyTorch_learning/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



##Introduction to tensors

### Creating tensors

tensors are created using torch.Tensor()
https://pytorch.org/docs/stable/tensors.html


In [ ]:
# scalar tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#scalar has got no dimensions
scalar.ndim

0

In [ ]:
#tensor as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]
                       ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

# 1 3 by 3 tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

In [ ]:
TENSOR_2 = torch.tensor([[[1,2,3],
                          [4,5,6],
                          [7,8,9],
                          [0,0,0]],
                         ])

In [ ]:
TENSOR_2.ndim

3

In [ ]:
TENSOR_2.shape

torch.Size([1, 4, 3])

### Random tensors

Why random tensors?

Random tensors are improtant because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

essentially it "makes guesses", compare with the raw data, then improves those guesses

In [ ]:
# Create a random tensor of shape/size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3377, 0.5654, 0.2498, 0.8685],
        [0.7957, 0.6732, 0.3032, 0.1831],
        [0.0896, 0.7550, 0.9317, 0.3678]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #represents height, width and color channels(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Tensors of zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype


torch.float32

### creating a range of tensors and tensors-like

In [ ]:
#torch.range()
#torch.range(0, 10) #might be removed
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_zeros.dtype

torch.int64

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors encountered with PyTorch & deep learning

1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device (GPU,CPU, etc)





In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, #tensors datatype, float16/32/64
                               device=None, #what device is your tensor on
                               requires_grad=False #whether or not to track gradients with this tensor operations 
                              )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor #diff datatypes but work, some operations will run into error

tensor([ 9., 36., 81.])

###Getting information from tensors

1.   Tensors not right datatype - to do get datatype from a tensor, use tensor.dtype
2.   Tensors not right shape - to get shape from a tensor, use tensor.shape
3.   Tensors not on the right device (GPU,CPU, etc) - to get device from a tensor, use tensor.device

In [ ]:
#create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0114, 0.1281, 0.5830, 0.3206],
        [0.1422, 0.7676, 0.4669, 0.6719],
        [0.2707, 0.1190, 0.5429, 0.1962]])

In [ ]:
# find out the information
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0114, 0.1281, 0.5830, 0.3206],
        [0.1422, 0.7676, 0.4669, 0.6719],
        [0.2707, 0.1190, 0.5429, 0.1962]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations:
* Additions
* Subtractions
* Mutiplication (ele wise)
* Division
* Matrix multiplication

In [ ]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
#immutable
tensor 

tensor([1, 2, 3])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication (this is scalar multiplication)
2. Matrix multiplication (iteration of dot products)

2 main rules to follow when doing mat mul, which is same as the theory of doing mat mul
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the outer dimensions



In [ ]:
 #ele wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication, the usual matrix mul
torch.matmul(tensor, tensor) #this will be 1x3 * 3x1 -> 1x1

tensor(14)

In [ ]:
%%time 
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.74 ms, sys: 0 ns, total: 2.74 ms
Wall time: 2.76 ms


In [ ]:
%%time 
torch.matmul(tensor, tensor)

CPU times: user 101 µs, sys: 0 ns, total: 101 µs
Wall time: 106 µs


tensor(14)

###so much faster using the torch functions to do mat mul

### one of the most common error is shape errors

In [ ]:
#shapes for mat mul
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]
                         ])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]
                         ])

torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the tensor shape issue, we can transpose of the the tensors

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## tensor aggregations, finding the min, max, mean, sum etc

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x) #mean cannot be used with long datatype

RuntimeError: ignored

In [ ]:
#change the datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding positional min and max

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])