<a href="https://colab.research.google.com/github/shecheeyee/PyTorch_learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_a = torch.rand(7,7)
tensor_a

tensor([[0.7546, 0.2014, 0.8329, 0.7504, 0.0680, 0.8529, 0.4794],
        [0.7747, 0.1551, 0.0834, 0.3218, 0.3010, 0.4393, 0.8009],
        [0.2790, 0.6427, 0.3009, 0.8293, 0.3420, 0.9107, 0.7345],
        [0.0739, 0.0888, 0.0487, 0.2900, 0.7007, 0.8923, 0.9649],
        [0.9873, 0.2337, 0.2469, 0.5513, 0.5290, 0.5060, 0.7998],
        [0.1227, 0.7915, 0.5302, 0.3625, 0.0256, 0.4721, 0.1667],
        [0.7791, 0.7209, 0.2947, 0.8355, 0.1460, 0.8069, 0.0580]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_b = torch.rand(1,7)
# Perform matrix multiplication 
result = torch.mm(tensor_a, tensor_b.T)
result

tensor([[2.3080],
        [1.1650],
        [2.1019],
        [1.6048],
        [1.7016],
        [1.2766],
        [1.9321]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(7, 7)
torch.manual_seed(RANDOM_SEED)
tensorB = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.mm(tensorA, tensorB.T)
result, result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]), torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed(RANDOM_SEED_GPU)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(RANDOM_SEED_GPU)


# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Create two random tensors on GPU
tensor_c = torch.rand(2, 3).to(device)
tensor_d = torch.rand(2, 3).to(device)
tensor_c, tensor_d

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(tensor_c, tensor_d.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
print(torch.max(result))
# Find min
print(torch.min(result))

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
print(result.argmax())

# Find arg min
print(result.argmin())

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
RANDOM_SEED_2 = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
tensor_e = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_f = tensor_e.squeeze()

# Print out tensors and their shapes
print(f"tensor_e: {tensor_e}, shape: {tensor_e.shape}")
print(f"tensor_f: {tensor_f}, shape: {tensor_f.shape}")


tensor_e: tensor([[[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
           0.4556, 0.6323]]]]), shape: torch.Size([1, 1, 1, 10])
tensor_f: tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
        0.6323]), shape: torch.Size([10])
